apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: quick-custom-postgres
spec:
  version: "custom-10.6"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate