apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: my-prometheus
spec:
  serviceAccountName: my-prometheus
  resources:
    requests:
      memory: 200Mi
  serviceMonitorSelector:
    matchLabels:
      prometheus: my-prometheus
  enableAdminAPI: false